FROM oven/bun:1-alpine AS builder

WORKDIR /app

COPY package.json bun.lockb ./
RUN bun install

COPY . .
RUN bun run build

FROM oven/bun:1-alpine AS runner

WORKDIR /app

RUN addgroup -g 1001 -S bunjs
RUN adduser -S bunjs -u 1001

COPY --from=builder /app/public ./public
COPY --from=builder --chown=bunjs:bunjs /app/.next/standalone ./
COPY --from=builder --chown=bunjs:bunjs /app/.next/static ./.next/static

USER bunjs

EXPOSE 3000

ENV PORT 3000

CMD ["bun", "server.js"]